version: '3.8'

services:
  backend:
    container_name: southerncode_api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    env_file:
    - .env
    volumes:
      - ".:/usr/src/web"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - api

  postgres:
    image: postgres:14-alpine
    container_name: southerncode_db
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - api
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: southerncode_pgadmin
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./pg_admin_data:/var/lib/pgadmin
    ports:
      - "9090:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    networks:
      - database

networks:
  api: {}
  database: {}

volumes:
  db_data: {}
  pg_admin_data: {}
